### ISSUE TITLE
List-of-files download format doesn't work

### ISSUE THREAD

**Issue by djcoleman** [release-engineering/offliner#34]
The list-of-files example, described as being the simplest possible input file in the docs, does not work with offliner 1.3. This is because the PlaintextArtifactListReader expects to be able to split each line into a checksum and path, and when a checksum is not present, the line is skipped. As a result, there are no files downloaded for the simple example.

To reproduce, copy the following lines to a file, example.txt
`/antlr/antlr/2.7.7/antlr-2.7.7.jar`
`/antlr/antlr/2.7.7/antlr-2.7.7.jar.sha1`

Then run offliner on this file:
`java -jar offliner-1.3.jar example.txt`

> Downloading artifacts from: example.txt
Nothing to download!
0 downloads succeeded.
0 downloads avoided.
0 downloads failed.

**Comment by jdcasey** [comment]
Out of curiosity, have you tried the csv-style <checksum>,<path> list-of-files format? I think I came across this older version of the format being broken once before, but at the time I believe that one worked. Is it possible to use this alternative format instead? It will provide a better user experience IMO, since it can recover from bad / partial downloads.

**Comment by djcoleman** [comment]
The csv-style file list does work, but I think I was trying to generate a manifest file from a directory listing using find. It wouldn't be that much work to generate the csv-style list, but I think the docs should be consistent with the functionality.

**Comment by jdcasey** [comment]
Agreed. I wasn't saying we should close this issue.
